# physixplore_streamlit_colored.py
"""
PhysiXplore - Smart Learning Hub for Modern Physics Education (Streamlit, Colorful)
Features:
- Colorful, PhET-style homepage with emojis
- Concepts: Motion, Energy, Electricity
- Lessons: Expanded explanations
- Quizzes: 5 items per topic, immediate feedback, save scores to scores.json
- Simulations: Projectile Motion, Energy Skate Park, Wave Visualizer (plots & animation)
- Footer with credits & contact placeholder

Author: Converted by ChatGPT for user "potpot"
"""

import streamlit as st
import json
import math
import time
from datetime import datetime
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt

SCORES_FILE = Path("scores.json")

# ---------------------------
# Helpers for scores storage
# ---------------------------
def load_scores():
    if SCORES_FILE.exists():
        try:
            return json.loads(SCORES_FILE.read_text())
        except Exception:
            return {}
    return {}

def save_score(topic, username, score, total):
    scores = load_scores()
    now = datetime.utcnow().isoformat() + "Z"
    if topic not in scores:
        scores[topic] = []
    scores[topic].append({"user": username, "score": score, "total": total, "time": now})
    SCORES_FILE.write_text(json.dumps(scores, indent=2))

# ---------------------------
# Quiz data
# ---------------------------
QUIZZES = {
    "Motion": [
        {"q":"An object moves at constant acceleration. u=0 m/s, a=2 m/s², distance in 3 s?","type":"numeric","answer":9.0,"explain":"s = ut + 1/2 a t^2 = 9 m."},
        {"q":"Rate of change of displacement?","type":"mcq","options":["Speed","Velocity","Acceleration","Jerk"],"answer":"Velocity","explain":"Velocity is the rate of change of displacement."},
        {"q":"Car goes 10→20 m/s in 5 s. Acceleration?","type":"numeric","answer":2.0,"explain":"a = (v-u)/t = 2 m/s²"},
        {"q":"Which graph shows constant acceleration?","type":"mcq","options":["Position-time straight","Velocity-time straight","Acceleration-time sinusoidal","Position-time horizontal"],"answer":"Velocity-time straight","explain":"Velocity-time straight line indicates constant acceleration."},
        {"q":"Drop two objects same height, no air resistance. Which hits first?","type":"mcq","options":["Heavier","Lighter","Both same","Depends on shape"],"answer":"Both same","explain":"Acceleration due to gravity is same for all masses."},
    ],
    "Energy": [
        {"q":"Kinetic energy formula?","type":"mcq","options":["mgh","1/2 m v^2","F s","p v"],"answer":"1/2 m v^2","explain":"KE = 1/2 m v^2."},
        {"q":"2 kg object moves 3 m/s. KE?","type":"numeric","answer":9.0,"explain":"KE = 1/2 m v^2 = 9 J."},
        {"q":"PE = mgh. m=1 kg, g=9.8, h=5 m. PE?","type":"numeric","answer":49.0,"explain":"PE = 1*9.8*5=49 J."},
        {"q":"Which process increases thermal energy?","type":"mcq","options":["Cooling","Friction work","Isothermal expansion","Adiabatic reversible"],"answer":"Friction work","explain":"Friction converts mechanical to thermal energy."},
        {"q":"Total mechanical energy (no friction)?","type":"mcq","options":["KE-PE","KE+PE","Only KE","Only PE"],"answer":"KE+PE","explain":"Mechanical energy = KE + PE."},
    ],
    "Electricity": [
        {"q":"Ohm's Law quantities?","type":"mcq","options":["Voltage,Current,Resistance","Power,Energy,Time","Charge,Mass,Velocity","Capacitance,Inductance,Resistance"],"answer":"Voltage,Current,Resistance","explain":"V=I*R"},
        {"q":"Resistor: 2A, 5V. R?","type":"numeric","answer":2.5,"explain":"R=V/I=2.5 Ω"},
        {"q":"Electric power formula?","type":"mcq","options":["P=V/I","P=I^2 R","P=V-I","P=R/I"],"answer":"P=I^2 R","explain":"Also P=V*I or V^2/R"},
        {"q":"SI unit of charge?","type":"mcq","options":["Volt","Ampere","Coulomb","Ohm"],"answer":"Coulomb","explain":"Unit is Coulomb (C)"},
        {"q":"Stores energy in electric field?","type":"mcq","options":["Inductor","Capacitor","Resistor","Transformer"],"answer":"Capacitor","explain":"Capacitor stores energy in electric field."},
    ]
}

# ---------------------------
# UI helpers
# ---------------------------
def header():
    st.markdown("<h1 style='color:#FF5733; text-align:center;'>⚡ PhysiXplore ⚡</h1>", unsafe_allow_html=True)
    st.markdown("<h4 style='color:#3498DB; text-align:center;'>Interactive Physics Learning Hub</h4>", unsafe_allow_html=True)
    st.markdown("---")

def footer():
    st.markdown("---")
    st.markdown("Contact: physixplore@example.com  |  Developer: potpot")
    st.markdown("© PhysiXplore — Generated by ChatGPT")

# ---------------------------
# Pages
# ---------------------------
def page_home():
    header()
    st.subheader("Highlights")
    cols = st.columns(3)
    cols[0].metric("🎢 Simulations", "Projectile, Energy Skate, Wave")
    cols[1].metric("📖 Lessons", "Guided examples & visualizations")
    cols[2].metric("📝 Quizzes", "Immediate feedback + save scores")
    st.markdown("### Quick Navigation")
    c1, c2, c3, c4 = st.columns(4)
    if c1.button("🏎 Motion"): st.session_state["page"]="concepts"
    if c2.button("⚡ Energy"): st.session_state["page"]="lessons"
    if c3.button("🔌 Electricity"): st.session_state["page"]="quizzes"
    if c4.button("🎢 Simulations"): st.session_state["page"]="sims"
    st.info("Featured: Projectile Motion, Energy Skate Park, Wave Visualizer")

def page_concepts():
    header()
    st.subheader("Concepts")
    topic = st.selectbox("Choose concept", ["Motion", "Energy", "Electricity"])
    if topic == "Motion":
        st.markdown("**Motion**: study of displacement, velocity, acceleration. Kinematics describes constant acceleration.")
        st.info("Try 'Projectile Motion' simulation 🎯.")
    elif topic == "Energy":
        st.markdown("**Energy**: KE, PE, thermal energy. Mechanical energy = KE + PE.")
        st.info("Try 'Energy Skate Park' simulation 🛹.")
    else:
        st.markdown("**Electricity**: charge, current, voltage, resistance. Ohm's law: V=IR, Power: P=VI")
    st.button("⬅ Back to Home", on_click=lambda: st.session_state.update(page="home"))

def page_lessons():
    header()
    st.subheader("Lessons & Guided Examples")
    st.markdown("### Motion 🏎\n- Displacement, velocity, acceleration\n- Example: Car accelerates 3 m/s² → v=15 m/s, d=37.5 m")
    st.markdown("### Energy ⚡\n- KE & PE calculations\n- Example: Mass=2 kg, speed=4 m/s → KE=16 J")
    st.markdown("### Electricity 🔌\n- Circuits, Ohm's law, Power\n- Example: V=12V, R=4Ω → I=3A, P=36W")
    st.button("⬅ Back to Home", on_click=lambda: st.session_state.update(page="home"))

def page_quizzes():
    header()
    st.subheader("Quizzes 📝")
    username = st.text_input("Your name", value=st.session_state.get("username","Guest"))
    st.session_state["username"] = username
    topic = st.selectbox("Select Topic", list(QUIZZES.keys()))
    if "quiz_active" not in st.session_state or st.session_state.get("quiz_topic") != topic:
        st.session_state["quiz_active"] = False
        st.session_state["quiz_topic"] = topic
    start = st.button("Start Quiz 🏁")
    if start or st.session_state.get("quiz_active"):
        st.session_state["quiz_active"] = True
        questions = QUIZZES[topic]
        qi = st.session_state.get("quiz_index",0)
        score = st.session_state.get("quiz_score",0)
        if qi >= len(questions):
            st.success(f"🎉 Quiz Complete! Score: {score}/{len(questions)}")
            if st.button("Save Score 💾"):
                save_score(topic, username or "Guest", score, len(questions))
                st.success("Saved ✅")
                st.session_state.update(quiz_active=False, quiz_index=0, quiz_score=0)
            if st.button("Back to Home ⬅"):
                st.session_state.update(page="home", quiz_active=False, quiz_index=0, quiz_score=0)
            return
        q = questions[qi]
        st.markdown(f"**Question {qi+1} of {len(questions)}**")
        st.write(q["q"])
        user_answer_key = f"ans_{topic}_{qi}"
        if q["type"]=="mcq": ans = st.radio("Choose answer", q["options"], key=user_answer_key)
        else: ans = st.text_input("Enter numeric answer", key=user_answer_key)
        col1,col2=st.columns(2)
        if col1.button("Submit Answer ✅"):
            correct=False
            if q["type"]=="mcq":
                if ans=="": st.warning("Select an option.")
                else: correct=(ans==q["answer"])
            else:
                if ans=="": st.warning("Enter a numeric answer.")
                else:
                    try: correct=math.isclose(float(ans), float(q["answer"]), rel_tol=1e-3, abs_tol=1e-3)
                    except: st.warning("Enter valid number."); correct=False
            if correct: st.success("✅ Correct!"); st.session_state["quiz_score"]=score+1
            else: st.error("❌ Incorrect.")
            st.info(f"💡 Explanation: {q.get('explain','No explanation.')}")
            st.session_state["quiz_index"]=qi+1
            st.experimental_rerun()
        if col2.button("Cancel Quiz ❌"):
            st.session_state.update(quiz_active=False,quiz_index=0,quiz_score=0)
            st.experimental_rerun()
    else: st.info("Press 'Start Quiz 🏁' to begin.")
    st.button("⬅ Back to Home", on_click=lambda: st.session_state.update(page="home"))

# ---------------------------
# Simulations
# ---------------------------
def sims_projectile():
    st.subheader("Projectile Motion Simulator 🎯")
    v0 = st.number_input("Initial speed (m/s)", value=20.0, step=0.5)
    angle_deg = st.number_input("Angle (deg)", value=45.0, step=1.0)
    g = 9.81
    if st.button("Run Projectile Simulation 🚀"):
        theta=math.radians(angle_deg)
        t_flight=2*v0*math.sin(theta)/g
        x=np.linspace(0,t_flight,200)
        y=v0*math.sin(theta)*x - 0.5*g*x**2 / math.cos(theta) # approximate
        st.write(f"Time of flight: {t_flight:.2f}s")
        fig,ax=plt.subplots(); ax.plot(x,y,'r-',lw=2); ax.fill_between(x,0,y,color='orange',alpha=0.3); st.pyplot(fig)

def sims_energy_skate():
    st.subheader("Energy Skate Park Simulator 🛹")
    m=st.number_input("Mass (kg)",1.0,step=0.1)
    h=st.number_input("Height (m)",5.0,step=0.1)
    v=st.number_input("Velocity (m/s)",0.0,step=0.1)
    g=9.81
    if st.button("Compute Energies ⚡"):
        pe=m*g*h; ke=0.5*m*v**2; st.success(f"PE={pe:.2f} J  KE={ke:.2f} J  Total={pe+ke:.2f} J")

def sims_wave():
    st.subheader("Wave Visualizer 🌊")
    A=st.number_input("Amplitude",1.0,step=0.1)
    f=st.number_input("Frequency (Hz)",1.0,step=0.1)
    duration=st.number_input("Duration (s)",2.0,step=0.5)
    if st.button("Plot Wave 🌈"):
        x=np.linspace(0,duration,400)
        y=A*np.sin(2*math.pi*f*x)
        fig,ax=plt.subplots(); ax.plot(x,y,'b-',lw=2); ax.fill_between(x,0,y,color='lightblue',alpha=0.3); st.pyplot(fig)

def sims_projectile_game():
    st.subheader("🚀 Projectile Motion - Animated")
    v0=st.slider("Speed (m/s)",5,50,20)
    angle_deg=st.slider("Angle (deg)",10,80,45)
    g=9.81
    if st.button("Launch 🚀"):
        theta=math.radians(angle_deg)
        t_flight=2*v0*math.sin(theta)/g
        t=np.linspace(0,t_flight,100)
        x=v0*np.cos(theta)*t
        y=v0*np.sin(theta)*t-0.5*g*t**2
        placeholder=st.empty()
        fig,ax=plt.subplots()
        ax.set_xlim(0,max(x)*1.1); ax.set_ylim(0,max(y)*1.1)
        line,=ax.plot([],[],'r-',lw=2)
        point,=ax.plot([],[],'bo',markersize=10)
        for i in range(len(t)):
            line.set_data(x[:i+1],y[:i+1])
            point.set_data(x[i],y[i])
            placeholder.pyplot(fig)
            time.sleep(0.05)

def sims_wave_game():
    st.subheader("🌊 Wave - Animated Sine")
    A=st.slider("Amplitude",0.1,5.0,1.0)
    f=st.slider("Frequency (Hz)",0.1,5.0,1.0)
    duration=2.0
    if st.button("Animate 🌈"):
        x=np.linspace(0,duration,400)
        placeholder=st.empty()
        fig,ax=plt.subplots()
        ax.set_xlim(0,duration); ax.set_ylim(-A*1.2,A*1.2)
        line,=ax.plot([],[],'b-',lw=2)
        for i in range(len(x)):
            y=A*np.sin(2*math.pi*f*x[:i+1])
            line.set_data(x[:i+1],y)
            placeholder.pyplot(fig)
            time.sleep(0.02)

def page_simulations():
    header()
    sim=st.radio("Choose simulation",["Projectile Motion 🎯","Energy Skate Park 🛹","Wave Visualizer 🌊","Projectile Motion Animated","Wave Animated"])
    if sim.startswith("Projectile Motion 🎯"): sims_projectile()
    elif sim.startswith("Energy Skate Park"): sims_energy_skate()
    elif sim.startswith("Wave Visualizer"): sims_wave()
    elif sim.startswith("Projectile Motion Animated"): sims_projectile_game()
    else: sims_wave_game()
    st.button("⬅ Back to Home",on_click=lambda: st.session_state.update(page="home"))

# ---------------------------
# Main
# ---------------------------
if "page" not in st.session_state: st.session_state["page"]="home"

page = st.session_state["page"]
if page=="home": page_home()
elif page=="concepts": page_concepts()
elif page=="lessons": page_lessons()
elif page=="quizzes": page_quizzes()
elif page=="sims": page_simulations()

footer()
